//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serwis_Muzyczny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public album()
        {
            this.przynaleznosc = new HashSet<przynaleznosc>();
        }
    
        public int albumId { get; set; }
        public string nazwa { get; set; }
        public System.DateTime dataWydania { get; set; }
        public int gatunekId { get; set; }
        public int artystaId { get; set; }
    
        public virtual artysta artysta { get; set; }
        public virtual gatunek gatunek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<przynaleznosc> przynaleznosc { get; set; }
    }
}
