//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serwis_Muzyczny.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public album()
        {
            this.przynaleznosc = new HashSet<przynaleznosc>();
        }

        public int albumId { get; set; }

        [Display(Name = "Tytu³")]
        [Required(ErrorMessage = "Tytu³ nie mo¿e byæ pusty")]
        [MaxLength(60, ErrorMessage = "Maksymalna d³ugoœæ tytu³u wynosi 60")]
        public string nazwa { get; set; }

        [Display(Name = "Data wydania")]
        [Required(ErrorMessage = "Data nie mo¿e byæ pusta")]
        /*
    A date formatted like YYYY-MM-DD could be something like 28-12-2013.
    And if we reverse the date, it is 2013-12-28.
    We remove the colons, and we get 20131228.
    We set an other date: 2013-11-27 which finally is 20131127.
    We can perform a simple operation: 20131228 - 20131127
*/

        [Serwis_Muzyczny.App_Start.Validation.FutureDate]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime dataWydania {get;set;}

        public Nullable<int> gatunekId { get; set; }
        public Nullable<int> artystaId { get; set; }
    
        public virtual artysta artysta { get; set; }
        public virtual gatunek gatunek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<przynaleznosc> przynaleznosc { get; set; }
    }
}
