//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serwis_Muzyczny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odsluch
    {
        public int odsluchId { get; set; }
        public string uzytkownikId { get; set; }
        public int utworId { get; set; }
        public System.DateTime dataOdtworzenia { get; set; }
    
        public virtual utwor utwor { get; set; }
        public virtual uzytkownik uzytkownik { get; set; }
    }
}
