//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serwis_Muzyczny.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class planUzytkownik
    {
        [DisplayName("Id")]
        public int planUzytkownikid { get; set; }
        [DisplayName("Id uzytkownika")]
        public string uzytkownikId { get; set; }
        [DisplayName("Id planu")]
        public int planId { get; set; }

        [DisplayName("Data kupna pakietu")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime dataKupnaPakietu { get; set; }

        [DisplayName("Rabat")]
        public Nullable<byte> rabat { get; set; }
    
        public virtual uzytkownik uzytkownik { get; set; }
        public virtual plany plany { get; set; }
    }
}
