//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serwis_Muzyczny.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class przynaleznosc
    {
        [DisplayName("Id")]
        public int przynaleznoscId { get; set; }
        [DisplayName("Id albumu")]
        public int albumId { get; set; }
        [DisplayName("Id utworu")]
        public int utworId { get; set; }
    
        public virtual album album { get; set; }
        public virtual utwor utwor { get; set; }
    }
}
