//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serwis_Muzyczny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class przynaleznosc
    {
        public int przynaleznoscId { get; set; }
        public Nullable<int> albumId { get; set; }
        public Nullable<int> utworId { get; set; }
    
        public virtual album album { get; set; }
        public virtual utwor utwor { get; set; }
    }
}
