//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serwis_Muzyczny.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class utwor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public utwor()
        {
            this.odsluch = new HashSet<odsluch>();
            this.przynaleznosc = new HashSet<przynaleznosc>();
            this.wykonanie = new HashSet<wykonanie>();
        }
    
        [DisplayName("Id utworu")]
        public int utworId { get; set; }
        [DisplayName("Nazwa")]
        public string nazwa { get; set; }
        [DisplayName("D³ugoœæ")]
        public string dlugosc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<odsluch> odsluch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<przynaleznosc> przynaleznosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wykonanie> wykonanie { get; set; }
    }
}
